language: python
python:
- "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install

script:
  - pytest
  - pytest --cov=ouf

after_success:
  - coveralls
